/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-08-23 16:46:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.BBS;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.ArrayList;

public final class bbs_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 //전역변수,전역함수
   //ssi.jsp문서는 단독실행가능합니다
   Connection CN; //DB서버연결정보,명령어생성할때 참조 
   Statement ST; //ST=CN.createStatement()
   PreparedStatement PST; //PST=CN.prepareStatment(sql)
   CallableStatement CS; //CS=CN.callableStatement(sql)
   ResultSet RS; //조회한결과를 RS기억  RS.next( )

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/BBS/../ssi.jsp", Long.valueOf(1661163652691L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

   try{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    String url="jdbc:oracle:thin:@127.0.0.1:1521:XE";
    CN=DriverManager.getConnection(url,"system", "1234");
    System.out.println("1단계: db connect Success");
    }catch(Exception ex){
        out.println("db err");
    }

      out.write('\r');
      out.write('\n');

    String loginUserEmail = (String)session.getAttribute("loginEmail");
    String sqlQuery;

    String email;
    String pw;
    String name;
    String profileimg ;

      out.write('\r');
      out.write('\n');

    sqlQuery = "select * from yunBbsUser where email =?";
    PST=CN.prepareStatement(sqlQuery);
    PST.setString(1, loginUserEmail);
    RS=PST.executeQuery();
    while(RS.next()){

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../CSS/bbs_main.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("    <title>Yunha's BBS</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"bbsTitle\" id=\"bbsTitle\">\r\n");
      out.write("        Welcome Yunha's BBS\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"board\">\r\n");
      out.write("        <div class=\"topBoard\">\r\n");
      out.write("            <div class=\"userBoard\">\r\n");
      out.write("                \r\n");
      out.write("                ");
if(session.getAttribute("loginEmail") != null){
      out.write("\r\n");
      out.write("                <ul class=\"userBoard00\">\r\n");
      out.write("                    <li class=\"userBoard01\">\r\n");
      out.write("                        <div class=\"img\">\r\n");
      out.write("                            <img src=\"../storage/");
      out.print(RS.getString("profileimg"));
      out.write("\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span class=\"material-symbols-outlined\" onclick=\"userUpdate()\">edit</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <li class=\"userBoard02\">\r\n");
      out.write("                        <div>EMAIL</div>\r\n");
      out.write("                        <div>");
      out.print(RS.getString("email"));
      out.write("</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"userBoard03\">\r\n");
      out.write("                        <div>NAME</div>\r\n");
      out.write("                        <div>");
      out.print(RS.getString("name"));
      out.write("</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"userBoard04\">\r\n");
      out.write("                        <div class=\"logoutBox\" onclick=\"logout(event)\">\r\n");
      out.write("                            <span class=\"material-icons\">power_settings_new</span>\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <small>Log-out</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("                <script>\r\n");
      out.write("                    function userUpdate(){\r\n");
      out.write("                        console.log(\"updateClick!\");\r\n");
      out.write("                    }\r\n");
      out.write("                    function logout(e){\r\n");
      out.write("                        fetch('../logout.jsp', {\r\n");
      out.write("                        }).then((res)=>{\r\n");
      out.write("                            location.reload();\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"bbsBoard\">\r\n");
      out.write("                <div class=\"bbsState\">전체 게시판</div>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>1</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>2022-10-10</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>2</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>3</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>4</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>5</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>6</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>7</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>8</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>9</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>10</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>11</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>12</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>13</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>14</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>        \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"\">\r\n");
      out.write("            <div class=\"search\">\r\n");
      out.write("            <label for=\"searchInput\">검색조건</label>\r\n");
      out.write("            <select name=\"select\">\r\n");
      out.write("                <option value=\"title\">제목</option>\r\n");
      out.write("                <option value=\"author\">글쓴이</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <input type=\"text\" id=\"searchInput\" name=\"searchInput\" placeholder=\"검색할 내용을 입력한 후 ENTER키를 입력하세요\" autocomplete=\"off\">\r\n");
      out.write("            <input type=\"submit\" value=\"검색\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"bbsView\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"viewBorder\">\r\n");
      out.write("                <div class=\"viewHeader\">\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    <table cellspacing=\"1\">\r\n");
      out.write("                        <thead class=\"thead\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th rowspan=\"2\" class=\"profileImg\"><img src=\"../storage/이준호.jpg\"></th>\r\n");
      out.write("                                <th>글 번호</th>\r\n");
      out.write("                                <th style=\"width: 250px;\">제목</th>\r\n");
      out.write("                                <th>글쓴이</th>\r\n");
      out.write("                                <th>날짜</th>\r\n");
      out.write("                                <td style=\"background-color: silver; cursor:pointer;\">수정</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>0</td>\r\n");
      out.write("                                <td>title</td>\r\n");
      out.write("                                <td>author</td>\r\n");
      out.write("                                <td>2022-08-23</td>\r\n");
      out.write("                                <td style=\"background-color: silver; cursor:pointer;\">삭제</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td colspan = \"6\">\r\n");
      out.write("                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae nihil placeat voluptatum magnam fugiat possimus sequi, sint ex saepe adipisci ducimus rerum laborum aliquid fugit eveniet illo, fuga aperiam eos.\r\n");
      out.write("                                    Repellendus repudiandae quidem amet ducimus quae nostrum vel ex quo laudantium odio quaerat laborum, eos cupiditate. Doloribus dolor, dignissimos dicta est dolorum quam deserunt alias veritatis nisi suscipit corrupti neque?\r\n");
      out.write("                                    Iste eligendi, pariatur sunt cupiditate deleniti porro perferendis eius, culpa obcaecati dicta voluptatem deserunt consequuntur? Quia, quae nihil nulla soluta laborum sit? Dignissimos quisquam esse tempore eum reiciendis aliquam delectus.\r\n");
      out.write("                                    Accusantium facere, nostrum, harum enim commodi sint expedita repudiandae, aut recusandae delectus voluptate nulla ipsam. Vero quis nobis vitae quidem nostrum repellendus excepturi, aut exercitationem ut eveniet modi, incidunt consectetur.\r\n");
      out.write("                                    Quas sed, ratione natus fugiat earum voluptas magnam facilis consequuntur sit quibusdam at rerum ea voluptate, ipsum voluptatum aliquam voluptatem inventore nostrum laboriosam vel. Pariatur voluptatibus itaque reprehenderit eius impedit?\r\n");
      out.write("                                    Repellat esse molestias expedita debitis in sequi sit, eaque accusamus aperiam aliquid at, quos nam! Minus nostrum labore nam eius blanditiis accusantium sunt pariatur dolores quae obcaecati, iure cum quam.\r\n");
      out.write("                                    Animi, placeat veritatis! Odio, facilis eius veritatis rem adipisci consequuntur harum accusantium quos tempora a voluptas, eum repellendus quod cumque optio delectus. Ipsam dolorum cum debitis temporibus reprehenderit aspernatur sit.\r\n");
      out.write("                                    Rerum architecto, corporis magnam beatae, voluptatibus sint at ratione quia omnis error eligendi qui ullam voluptate nemo eveniet, corrupti et fugit unde modi aliquam? Doloribus repudiandae odit deleniti inventore alias?\r\n");
      out.write("                                    Sunt animi ullam porro beatae nihil. Voluptatum distinctio, nostrum quos laudantium reiciendis sunt doloremque exercitationem expedita nihil atque illo aliquam amet, eveniet aliquid non debitis dicta. Quibusdam nihil illum deleniti.\r\n");
      out.write("                                    Eaque voluptatibus perspiciatis blanditiis magni, voluptates veritatis consectetur quo ab quasi qui deleniti commodi repellendus odit consequatur a! Dolor corporis fuga deserunt voluptas. Velit inventore doloribus atque error! Fugit, ducimus.\r\n");
      out.write("                                    Corporis, consequuntur optio. Vero, accusantium earum qui dolores accusamus dolorum optio perspiciatis nihil, voluptates unde illo, sequi officia nulla natus iure laboriosam eius nobis blanditiis. Perspiciatis, aperiam? Dignissimos, cumque facilis?\r\n");
      out.write("                                    Quod reiciendis culpa quos commodi aperiam delectus totam quo, fugit exercitationem molestias laboriosam beatae dolore, neque nostrum eaque libero quisquam nemo odit esse. Nobis sit odit voluptatibus veritatis consectetur eveniet?\r\n");
      out.write("                                    Ducimus, aliquid sunt facilis aliquam qui, obcaecati nulla perspiciatis doloremque repudiandae, laboriosam excepturi. Repellat accusantium atque dolor, blanditiis vel odio recusandae quasi architecto sed, facilis, cupiditate hic! Vero, necessitatibus eaque?\r\n");
      out.write("                                    Beatae at nesciunt labore facilis provident odit, aut repudiandae quia vel corporis asperiores minima expedita assumenda fuga quod cupiditate maiores sapiente animi! Nam dignissimos necessitatibus nemo fuga minima natus doloremque?\r\n");
      out.write("                                    Sed voluptates nulla eveniet qui soluta eum voluptatum deleniti fugiat commodi, quisquam reprehenderit facilis perspiciatis vitae nesciunt rerum alias repellendus maxime nemo harum accusantium? Voluptatibus non quidem corporis dolore nemo.\r\n");
      out.write("                                    Ab placeat voluptatem enim vero exercitationem alias maiores iure esse temporibus facere nisi minus facilis, ut similique repellendus? Nisi eius dolores veritatis est quasi qui dolorum voluptatibus tempore, rem unde.\r\n");
      out.write("                                    Nobis quae a voluptatem natus? Libero voluptatum maxime dolores ab non sapiente similique corporis, nostrum ducimus impedit! Voluptatibus, itaque dolorem vel fuga facere rerum error tempora exercitationem quo commodi neque!\r\n");
      out.write("                                    Nostrum sunt cum perspiciatis quisquam reprehenderit. Eos voluptate voluptatum culpa tempore doloribus illo corporis, nam id illum sint obcaecati accusantium aut consequuntur neque praesentium alias dolore quibusdam? Illum, quasi ad?\r\n");
      out.write("                                    Labore numquam eos fugiat sint facere, vitae dolorem eius sunt impedit. Harum perspiciatis debitis vel magni sint adipisci culpa. Asperiores nemo eligendi cum a impedit adipisci, nihil possimus obcaecati commodi?\r\n");
      out.write("                                    Consequatur corrupti eligendi nulla ut laboriosam, impedit dolorem odio, iure distinctio cumque asperiores eaque at dolores officiis, mollitia quidem voluptatum aliquam? Optio minus dolore tenetur aperiam a iusto architecto voluptatum.\r\n");
      out.write("                                    Quam beatae qui, minus dignissimos magni asperiores inventore, ipsum hic iste quod iusto aspernatur. Unde beatae, laboriosam repellendus eaque quos culpa soluta, ipsam, eos autem officia possimus mollitia iste vitae?\r\n");
      out.write("                                    Repudiandae perferendis voluptas cupiditate, nesciunt voluptates eligendi laudantium, dolorem temporibus hic incidunt reprehenderit nostrum fugiat sit optio, at doloremque delectus? Recusandae odit inventore ea esse architecto beatae quibusdam dicta mollitia.\r\n");
      out.write("                                    Officia laborum fugiat ad asperiores ea ratione voluptatibus. Quos beatae recusandae quibusdam illum excepturi! Neque, sapiente quas ex minima nesciunt veniam vitae impedit necessitatibus tempore doloremque molestiae, enim est voluptatibus.\r\n");
      out.write("                                    Voluptates sunt sit esse placeat modi iusto inventore alias qui doloribus laboriosam ducimus beatae dolores hic atque, voluptas pariatur autem nihil quidem distinctio exercitationem quod! Dicta omnis quis rerum error?\r\n");
      out.write("                                    Corporis a delectus numquam harum quaerat quasi accusamus! Rem, neque odio eligendi eveniet consequuntur tempora voluptatem voluptate labore velit numquam quibusdam deserunt nesciunt, dolorum, modi odit voluptas? Dolor, impedit in?\r\n");
      out.write("                                    Nulla illum sapiente voluptatibus aspernatur inventore eos eum, nesciunt ea, eaque optio totam est temporibus rem praesentium quod veniam quae corrupti laborum nisi qui itaque officia distinctio minus at. Fuga?\r\n");
      out.write("                                    Beatae praesentium doloremque similique sed maxime porro! Quae sunt nesciunt numquam mollitia saepe dicta, magnam, obcaecati corporis veritatis eum recusandae nemo dolor explicabo, assumenda quas atque odio dolorem asperiores voluptates?\r\n");
      out.write("                                    Recusandae quae soluta blanditiis repellendus dolor quo necessitatibus quos, at facere natus laborum voluptatem minima! Tenetur non, reiciendis molestias rerum veniam aperiam ratione mollitia velit placeat corrupti, ex sapiente deserunt!\r\n");
      out.write("                                    Repudiandae molestias ullam vel vero error animi nam exercitationem porro, modi ex assumenda natus voluptatem, nesciunt molestiae nobis pariatur velit quibusdam aperiam autem quo fugit enim. Officiis labore aperiam tenetur?\r\n");
      out.write("                                    Perferendis corporis facere deserunt quod, sed odio illum autem consequuntur sapiente sit assumenda repudiandae atque blanditiis ab eos nostrum nihil, vitae eius rerum mollitia illo eaque exercitationem. Ducimus, molestias ab.\r\n");
      out.write("                                    Ea, error autem! Alias praesentium, numquam architecto amet fugiat animi sit necessitatibus repellat aliquam totam quibusdam officia at recusandae eius facere quia vel doloribus cum. Temporibus et adipisci laudantium pariatur.\r\n");
      out.write("                                    Molestiae incidunt minima eligendi dolor. Consectetur est doloribus labore maiores ex esse inventore perferendis ullam omnis autem. Pariatur quam, numquam iure commodi debitis omnis vero, voluptate odit eius, mollitia nesciunt.\r\n");
      out.write("                                    A laudantium molestiae cupiditate tempore atque dignissimos vitae officiis recusandae corrupti dolore, mollitia, culpa aliquid tenetur provident corporis labore reprehenderit amet? Exercitationem enim commodi maxime autem sapiente eius eum nemo?\r\n");
      out.write("                                    Non facere autem veritatis deserunt suscipit necessitatibus rem iste quasi alias a nobis ea, modi, aliquid debitis numquam placeat assumenda. Nemo nostrum dolor ut quas animi deleniti unde magnam totam.\r\n");
      out.write("                                    Perspiciatis obcaecati laboriosam cum optio deserunt minus, enim corrupti? Officia nesciunt ipsam vel excepturi earum neque deserunt fugit architecto iste nulla, expedita velit pariatur repellendus rem voluptas reiciendis quae nam!\r\n");
      out.write("                                    Modi voluptates a quis voluptate sit nihil cumque quisquam consectetur laudantium. Dolores consequatur nam corporis quisquam, esse, pariatur laboriosam maiores odit iste eos, neque fuga deleniti voluptatem? Veritatis, nam iste?\r\n");
      out.write("                                    Accusamus dolorum rerum facilis! Aut, ipsa voluptatum, doloremque incidunt aliquid error magni fugiat dignissimos optio maiores sunt beatae ab nam deleniti enim corporis. Quasi, dolorem! Dolore vitae earum molestias alias!\r\n");
      out.write("                                    Pariatur, architecto repellendus. Iure magnam ipsum temporibus minus? Quos et aliquam officiis debitis! Reiciendis omnis dolorem dicta a consectetur aliquid expedita ipsa veniam, ducimus accusantium, eius cumque dolor, voluptas mollitia?\r\n");
      out.write("                                    Enim mollitia magnam aliquam repellat doloremque natus sint, sit praesentium voluptatum a numquam exercitationem accusamus voluptatibus? Illo enim dolor quam consectetur neque ducimus inventore adipisci fugit, facilis sint quisquam hic.\r\n");
      out.write("                                    Cupiditate temporibus iste libero ipsum expedita placeat dolor! Consequuntur similique quasi, ipsa consequatur in vitae fugiat pariatur nam temporibus reiciendis tenetur ratione a quidem nobis nostrum natus perferendis illo recusandae?\r\n");
      out.write("                                    Eum, vitae laudantium? Officiis inventore excepturi, esse sed omnis voluptate ea laborum vitae odit officia sapiente, deserunt aliquam illum nihil fuga obcaecati asperiores pariatur sunt? Velit hic molestiae harum accusamus?\r\n");
      out.write("                                    Veritatis perferendis neque, voluptas facilis aliquam atque repudiandae sunt ipsa consectetur unde corporis error ipsum earum perspiciatis veniam alias mollitia nisi iure ab similique sint architecto laborum. Optio, sed dolore?\r\n");
      out.write("                                    Laborum iusto odio assumenda distinctio maiores quod, voluptate aspernatur quia sed quam alias placeat nisi eum. Assumenda neque cupiditate iure esse, odio perspiciatis numquam harum aut, repellendus culpa ea similique.\r\n");
      out.write("                                    Qui officiis tempora eaque, magnam quam beatae blanditiis, at voluptatum aut sapiente corrupti amet. Assumenda exercitationem quos consequuntur veritatis. Totam quae et fuga voluptatum magni. Sequi aspernatur hic ipsa fuga?\r\n");
      out.write("                                    Pariatur praesentium minima optio eos numquam sapiente perspiciatis illum deleniti, deserunt, repellendus aliquid quos quisquam odit aspernatur illo architecto ipsa reiciendis asperiores itaque nostrum perferendis! Nesciunt sapiente debitis voluptate ab!\r\n");
      out.write("                                    Cum cupiditate est dolorum dignissimos pariatur aspernatur perspiciatis. Officia fugit voluptatum alias sed accusamus facilis pariatur itaque sint aliquid quos qui veniam illo quibusdam, ab ex dignissimos doloribus tempora quidem?\r\n");
      out.write("                                    Laudantium accusamus nostrum, numquam doloremque facere, vitae minus culpa earum corporis fugiat suscipit dicta quos nisi. Adipisci dolores sit, et porro debitis incidunt! Totam maxime voluptates eveniet saepe iste nostrum.\r\n");
      out.write("                                    Illo, architecto iste? Omnis dolor praesentium, consectetur eveniet ratione nam, quis et modi dignissimos nulla consequuntur labore amet voluptates dicta provident, molestiae quaerat. Quas repellat molestias consectetur at cupiditate. Ut.\r\n");
      out.write("                                    Corporis aperiam iure dolorum vitae possimus voluptatum nostrum non dolores ratione reprehenderit atque nulla magnam quasi harum quae tenetur asperiores voluptate sunt rerum perspiciatis consequatur, optio deserunt a. Molestiae, iusto.\r\n");
      out.write("                                    Autem delectus sit ipsum maiores aut a sunt ad ut sapiente eius vero alias obcaecati veritatis doloremque quae nulla, voluptatibus quos tempora perferendis impedit aliquam exercitationem? Nesciunt ut aperiam laboriosam!\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    <img src=\"../storage/우영우.jpg\" style=\"max-width:950px; max-height:500px;\">\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"write\">\r\n");
      out.write("            <div class=\"writeForm\">\r\n");
      out.write("                <form action=\"\">\r\n");
      out.write("                    <label for=\"title\">제목: </label>\r\n");
      out.write("                    <input type=\"text\" name=\"title\" id=\"title\" placeholder=\"제목을 입력하세요\">\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <label for=\"file\">사진: </label>\r\n");
      out.write("                    <input type=\"file\" name=\"file\" id=\"file\">\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <label for=\"content\">내용</label>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <textarea name=\"content\" id=\"content\"></textarea>\r\n");
      out.write("                    <input type=\"submit\" value=\"글 등록\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navbar\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li onclick=\"window.scrollTo({top: 1900, behavior: 'smooth',})\"><span class=\"material-symbols-outlined\">edit_square</span></li>\r\n");
      out.write("            <li onclick=\"window.scrollTo({top: 400, behavior: 'smooth',})\"><span class=\"material-symbols-outlined\">search</span></li>\r\n");
      out.write("            <li onclick=\"location.href='../index.jsp'\"><span class=\"material-symbols-outlined\">home</span></li>\r\n");
      out.write("            <li onclick=\"window.scrollTo({top: 0, behavior: 'smooth',})\"><span class=\"material-symbols-outlined\">arrow_circle_up</span></li>\r\n");
      out.write("            <li onclick=\"window.scrollTo({top: 3000, behavior: 'smooth',})\"><span class=\"material-symbols-outlined\">favorite</span></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"area\">\r\n");
      out.write("        <ul class=\"circles\">\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <div class=\"footh\">\r\n");
      out.write("            Kyungil University - Department of Computer Engineering\r\n");
      out.write("            <br>\r\n");
      out.write("            Made by. Woo yun ha \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footb\">\r\n");
      out.write("            <div class=\"sheepIcon\"></div>\r\n");
      out.write("            <div class=\"sheepIcon2\"></div>\r\n");
      out.write("            <div class=\"sheepIcon3\"></div>\r\n");
      out.write("            <div class=\"sheepIcon4\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
}
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
