/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-08-22 14:20:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.BBS;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.ArrayList;

public final class bbs_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 //전역변수,전역함수
   //ssi.jsp문서는 단독실행가능합니다
   Connection CN; //DB서버연결정보,명령어생성할때 참조 
   Statement ST; //ST=CN.createStatement()
   PreparedStatement PST; //PST=CN.prepareStatment(sql)
   CallableStatement CS; //CS=CN.callableStatement(sql)
   ResultSet RS; //조회한결과를 RS기억  RS.next( )

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/BBS/../ssi.jsp", Long.valueOf(1661163652691L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

   try{
    Class.forName("oracle.jdbc.driver.OracleDriver");
    String url="jdbc:oracle:thin:@127.0.0.1:1521:XE";
    CN=DriverManager.getConnection(url,"system", "1234");
    System.out.println("1단계: db connect Success");
    }catch(Exception ex){
        out.println("db err");
    }

      out.write('\r');
      out.write('\n');

    String loginUserEmail = (String)session.getAttribute("loginEmail");
    String sqlQuery;

    String email;
    String pw;
    String name;
    String profileimg ;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../CSS/bbs_main.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("    <title>Yunha's BBS</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"bbsTitle\" id=\"bbsTitle\">\r\n");
      out.write("        Welcome Yunha's BBS\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"board\">\r\n");
      out.write("        <div class=\"topBoard\">\r\n");
      out.write("            <div class=\"userBoard\">\r\n");
      out.write("                ");

                sqlQuery = "select * from yunBbsUser where email =?";
                PST=CN.prepareStatement(sqlQuery);
                PST.setString(1, loginUserEmail);
                RS=PST.executeQuery();
                
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                ");
if(session.getAttribute("loginEmail") != null){
      out.write("\r\n");
      out.write("                ");
while(RS.next()){
      out.write("\r\n");
      out.write("                <ul class=\"userBoard00\">\r\n");
      out.write("                    <li class=\"userBoard01\">\r\n");
      out.write("                        <div class=\"img\">\r\n");
      out.write("                            <img src=\"../storage/");
      out.print(RS.getString("profileimg"));
      out.write("\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <span class=\"material-symbols-outlined\" onclick=\"userUpdate()\">edit</span>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <li class=\"userBoard02\">\r\n");
      out.write("                        <div>EMAIL</div>\r\n");
      out.write("                        <div>");
      out.print(RS.getString("email"));
      out.write("</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"userBoard03\">\r\n");
      out.write("                        <div>NAME</div>\r\n");
      out.write("                        <div>");
      out.print(RS.getString("name"));
      out.write("</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"userBoard04\">\r\n");
      out.write("                        <div class=\"logoutBox\" onclick=\"logout(event)\">\r\n");
      out.write("                            <span class=\"material-icons\">power_settings_new</span>\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <small>Log-out</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("                <script>\r\n");
      out.write("                    function userUpdate(){\r\n");
      out.write("                        console.log(\"updateClick!\");\r\n");
      out.write("                    }\r\n");
      out.write("                    function logout(e){\r\n");
      out.write("                        fetch('../logout.jsp', {\r\n");
      out.write("                        }).then((res)=>{\r\n");
      out.write("                            location.reload();\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"bbsBoard\">\r\n");
      out.write("                <div class=\"bbsState\">전체 게시판</div>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>1</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>2022-10-10</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>2</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>3</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>4</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>5</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>6</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>7</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>8</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>9</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>10</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>11</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>12</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>13</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>14</div>\r\n");
      out.write("                        <div>title<span>picture</span><span>comm</span></div>\r\n");
      out.write("                        <div>author</div>\r\n");
      out.write("                        <div>date</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>        \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"\">\r\n");
      out.write("            <div class=\"search\">\r\n");
      out.write("            <label for=\"searchInput\">검색조건</label>\r\n");
      out.write("            <select name=\"select\">\r\n");
      out.write("                <option value=\"title\">제목</option>\r\n");
      out.write("                <option value=\"author\">글쓴이</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <input type=\"text\" id=\"searchInput\" name=\"searchInput\" placeholder=\"검색할 내용을 입력한 후 ENTER키를 입력하세요\">\r\n");
      out.write("            <input type=\"submit\" value=\"검색\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"bbsView\">\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"write\">\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navbar\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li onclick=\"window.scrollTo({top: 1900, behavior: 'smooth',})\"><span class=\"material-symbols-outlined\">edit_square</span></li>\r\n");
      out.write("            <li onclick=\"window.scrollTo({top: 400, behavior: 'smooth',})\"><span class=\"material-symbols-outlined\">search</span></li>\r\n");
      out.write("            <li onclick=\"location.href='../index.jsp'\"><span class=\"material-symbols-outlined\">home</span></li>\r\n");
      out.write("            <li><span class=\"material-symbols-outlined\">notifications</span></li>\r\n");
      out.write("            <li onclick=\"window.scrollTo({top: 0, behavior: 'smooth',})\"><span class=\"material-symbols-outlined\">arrow_circle_up</span></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"area\">\r\n");
      out.write("        <ul class=\"circles\">\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("            <li></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
